### ISSUE TITLE
Doc explaining border not updated!

### ISSUE THREAD

**Issue by SwaroopSomanna** [ghost1372/HandyControl-English-Documents#1]
The [doc](https://hosseini.ninja/handycontrol/native_controls/border/) explaining border is not updated with all available border styles.  
E.g: BorderRegion style is not mentioned in available styles.

**Comment by ghost1372** [comment]
Done in https://github.com/ghost1372/HandyControl-English-Documents/commit/a583b59e96c62297b46fead6131698aefd9e216d
site is updated
